# Automatically generated file. DO NOT MODIFY
#
# This file is generated by device/samsung/d1x/setup-makefiles.sh

LOCAL_PATH := $(call my-dir)

ifeq ($(TARGET_DEVICE),d1x)

$(call add-radio-file-sha1-checked,radio/cm.bin_SM-N971N,57dab058b20145fe48fc90ea654c8abb02ad118e)
$(call add-radio-file-sha1-checked,radio/dqmdbg.img_SM-N971N,d9f65b11623b7c917cf007f9fcab59b29246d7a8)
$(call add-radio-file-sha1-checked,radio/keystorage.bin_SM-N971N,e17979841f0106ee198c2da7a864ad7e19f93595)
$(call add-radio-file-sha1-checked,radio/models,ce1091c8b3e0998f48145fc55bbcf47ff417d5ad)
$(call add-radio-file-sha1-checked,radio/modem.bin_SM-N971N,cfabed9f5d27289cdf7fe9e665b0f71042cca1db)
$(call add-radio-file-sha1-checked,radio/modem_5g.bin_SM-N971N,789d5aa5caf15ee0820d22861f00a216a1a4617f)
$(call add-radio-file-sha1-checked,radio/modem_debug.bin_SM-N971N,d60b151798abb7ed32df0d3622c826e779817ca8)
$(call add-radio-file-sha1-checked,radio/modem_debug_5g.bin_SM-N971N,e2064f9c568bbf33c3fe4c00b36a6035925a882c)
$(call add-radio-file-sha1-checked,radio/param.bin_SM-N971N,34b2949d086dc083c3002c9db69c47aa644a454b)
$(call add-radio-file-sha1-checked,radio/sboot.bin_SM-N971N,a43a9584485b0ddc1e64a0f856564eb07421d0be)
$(call add-radio-file-sha1-checked,radio/uh.bin_SM-N971N,588352b9dd200dda3f1177a5a1b5016a3d8a6929)
$(call add-radio-file-sha1-checked,radio/up_param.bin_SM-N971N,edf02798d5bf2e767dd6c83a01b939fa0523d0b3)
$(call add-radio-file-sha1-checked,radio/version_SM-N971N,bb65baff6f760245e726aa8cbb3286ad87dffe98)

endif
