# Automatically generated file. DO NOT MODIFY
#
# This file is generated by device/samsung/d1x/setup-makefiles.sh

LOCAL_PATH := $(call my-dir)

ifeq ($(TARGET_DEVICE),d1x)

$(call add-radio-file-sha1-checked,radio/cm.bin_SM-N971N,66f9f24a70e3ecdd8245c949a93f8cebf6aa1f87)
$(call add-radio-file-sha1-checked,radio/dqmdbg.img_SM-N971N,c922576e0214f5482681e6922b793157a9adb746)
$(call add-radio-file-sha1-checked,radio/keystorage.bin_SM-N971N,49998e278ddf22a7a21887c4b14912aa67823c61)
$(call add-radio-file-sha1-checked,radio/models,ce1091c8b3e0998f48145fc55bbcf47ff417d5ad)
$(call add-radio-file-sha1-checked,radio/modem.bin_SM-N971N,28cde789ca167c2790bc9aee59cd570a6ee94ef9)
$(call add-radio-file-sha1-checked,radio/modem_5g.bin_SM-N971N,f39a13249cbf01b56920115d256c67bc192133b5)
$(call add-radio-file-sha1-checked,radio/modem_debug.bin_SM-N971N,8a51d25db011e4320574c17d18bbdac60813d1ab)
$(call add-radio-file-sha1-checked,radio/modem_debug_5g.bin_SM-N971N,ff661340e8be3911c095ba8dabb0b68669f6deff)
$(call add-radio-file-sha1-checked,radio/param.bin_SM-N971N,c2a26d5a291f00198afcfd9dc1929b0a996139e5)
$(call add-radio-file-sha1-checked,radio/sboot.bin_SM-N971N,c6a3e00edabe02b3dd5c1c8fe6926febade1cc3b)
$(call add-radio-file-sha1-checked,radio/uh.bin_SM-N971N,08c42aa2010358d3a1925133c5c8197a49608559)
$(call add-radio-file-sha1-checked,radio/up_param.bin_SM-N971N,64577c105cb7523747257f6b4153d256e31d2df0)
$(call add-radio-file-sha1-checked,radio/version_SM-N971N,c3cd6bd57a180959f1a9cb42035f67c621f1f0c2)

endif
